### ISSUE TITLE
Latest repo not working?

### ISSUE THREAD

**Issue by wdcurry** [aleksandrshoshiashvili/AwesomeTextFieldSwift#10]
I just dropped this into my test Swift project and the repo and the demo are failing, even after conversion. My project reported around 30+ errors.

Just an fyi.  thx..

**Comment by aleksandrshoshiashvili** [comment]
@wdcurry which version of swift are you using?  You can check it in terminal: open the Terminal and write:
`swift -version`

Btw: seems like recent changes broke project.pbxproj file. Already fix it, you can try again :)

**Comment by wdcurry** [comment]
Apple Swift version 3.1 (swiftlang-802.0.53 clang-802.0.42)
Target: x86_64-apple-macosx10.9

**Comment by aleksandrshoshiashvili** [comment]
@wdcurry thanks for answer. Try download project now, it should work for swift 3.1

**Comment by wdcurry** [comment]
Thank you .. i could not wait for a solution due to time constraints, and had offered this as an fyi, but thank you, i am sure others will benefit from your efforts!
