### ISSUE TITLE
UIView's height had some error?

### ISSUE THREAD

**Issue by rexzhang** [aleksandrshoshiashvili/AwesomeTextFieldSwift#3]
before the input
![simulator screen shot 2016 7 27 14 08 58](https://cloud.githubusercontent.com/assets/238707/17165552/bea6d5bc-5403-11e6-89c0-e374d01aee86.png)

after
![simulator screen shot 2016 7 27 14 04 00](https://cloud.githubusercontent.com/assets/238707/17165465/29183ea0-5403-11e6-99f3-3e1f48ae23e2.png)

MacOSX 10.11.5
XCode 7.3.1
AwesomeTextField  0.1.0 (install from cocoapods 0.1.0)

**Comment by antonioreyna** [comment]
have the same problem

**Comment by afrex** [comment]
@antonioreyna & @rexzhang try to increase your textfield height constraint to something big. For example a constant of 60

<img width="738" alt="screen shot 2017-05-23 at 23 13 27" src="https://cloud.githubusercontent.com/assets/1213533/26376648/8b585bf8-400d-11e7-897c-8fc80d92643c.png">

**Comment by aleksandrshoshiashvili** [comment]
@antonioreyna, @rexzhang you should increase textfield height because of placeholder is part of TextField and you need to take into account his height in active state
